export interface PolarDataset {
  id: string;
  title: string;
  station: 'Himadri' | 'Maitri' | 'Bharati';
  stationSlug: 'himadri' | 'maitri' | 'bharati';
  region: 'Arctic' | 'Antarctica';
  datasetType: string;
  scientificDomain: 'Atmosphere' | 'Cryosphere' | 'Ocean' | 'Geophysics' | 'Environment';
  description: string;
  dateStart: string;
  dateEnd: string;
  variables: string[];
  units: string[];
  fileFormat: string;
  source: 'National Polar Data Centre (NCPOR)';
  officialSourceUrl: 'https://npdc.ncpor.res.in/';
}

export const REAL_NPDC_DATASETS: PolarDataset[] = [
  // ===== MAITRI DATASETS =====
  {
    id: 'maitri-imd-surface-meteorology',
    title: 'Maitri Long-Term Surface Meteorological Observations (IMD)',
    station: 'Maitri',
    stationSlug: 'maitri',
    region: 'Antarctica',
    datasetType: 'Meteorology',
    scientificDomain: 'Atmosphere',
    description: 'Continuous 35-year surface meteorological record collected at Maitri Station in Schirmacher Oasis by the India Meteorological Department (IMD) & NCPOR. Tracks air temperature, barometric pressure, and wind velocity.',
    dateStart: '1985-01-01',
    dateEnd: '2019-12-31',
    variables: ['Air Temperature', 'Atmospheric Pressure', 'Wind Speed'],
    units: ['°C', 'hPa', 'm/s'],
    fileFormat: 'CSV / NetCDF',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'maitri-sankalp-sase-meteorology',
    title: 'Maitri SASE Automatic Weather Station (SASE SANKALP)',
    station: 'Maitri',
    stationSlug: 'maitri',
    region: 'Antarctica',
    datasetType: 'Meteorology & Snow Physics',
    scientificDomain: 'Atmosphere',
    description: 'High-precision Automatic Weather Station (AWS) records from Snow and Avalanche Study Establishment (SASE) at Maitri, monitoring extreme polar microclimates.',
    dateStart: '2006-02-23',
    dateEnd: '2019-12-31',
    variables: ['Air Temperature', 'Atmospheric Pressure', 'Wind Speed', 'Relative Humidity'],
    units: ['°C', 'hPa', 'm/s', '%'],
    fileFormat: 'CSV / NetCDF',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'maitri-hydrographic-lakes',
    title: 'Maitri Schirmacher Oasis Lakes Hydrographic Profiles',
    station: 'Maitri',
    stationSlug: 'maitri',
    region: 'Antarctica',
    datasetType: 'Hydrography',
    scientificDomain: 'Environment',
    description: 'Hydrographic depth, temperature, conductivity, and dissolved oxygen profiles across Priyadarshini and freshwater lakes in Schirmacher Oasis.',
    dateStart: '2013-01-01',
    dateEnd: '2018-12-31',
    variables: ['Lake Depth', 'Water Temperature', 'Conductivity', 'Dissolved Oxygen'],
    units: ['m', '°C', 'µS/cm', 'mg/L'],
    fileFormat: 'XLSB / Excel',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'maitri-high-speed-wind',
    title: 'Maitri Ultrasonic Anemometer High-Speed Katabatic Wind Array',
    station: 'Maitri',
    stationSlug: 'maitri',
    region: 'Antarctica',
    datasetType: 'Meteorology',
    scientificDomain: 'Atmosphere',
    description: 'High-frequency ultrasonic anemometer recordings measuring extreme katabatic wind gusts and severe blizzard velocities across the continental ice boundary.',
    dateStart: '2015-01-01',
    dateEnd: '2019-12-31',
    variables: ['Peak Wind Gust', 'Mean Wind Speed', 'Wind Vector Direction'],
    units: ['m/s', 'm/s', 'deg'],
    fileFormat: 'ZIP / Binary Logs',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'maitri-ott-precipitation-2019',
    title: 'Maitri OTT Pluvio Laser Disdrometer Precipitation Records (2019)',
    station: 'Maitri',
    stationSlug: 'maitri',
    region: 'Antarctica',
    datasetType: 'Meteorology',
    scientificDomain: 'Atmosphere',
    description: 'Laser optical disdrometer monitoring real-time precipitation intensity, snow particle spectrum, and optical visibility during polar storms.',
    dateStart: '2019-01-01',
    dateEnd: '2019-12-31',
    variables: ['Precipitation Rate', 'MOR Visibility', 'Particle Count'],
    units: ['mm/h', 'm', 'count'],
    fileFormat: 'ZIP / CSV',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },

  // ===== HIMADRI DATASETS =====
  {
    id: 'himadri-black-carbon-aerosols',
    title: 'Himadri High Arctic Optical Black Carbon Aerosol Time Series',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Black Carbon & Aerosols',
    scientificDomain: 'Atmosphere',
    description: 'Magee Aethalometer 7-wavelength observation of black carbon aerosol concentrations in Ny-Ålesund, Svalbard, monitoring long-range atmospheric pollution transport into the High Arctic.',
    dateStart: '2010-07-10',
    dateEnd: '2021-12-31',
    variables: ['Black Carbon Concentration', 'Spectral Attenuation (370-950nm)', 'Air Flow Rate'],
    units: ['ng/m³', '1/m', 'L/min'],
    fileFormat: 'CSV / Tar.gz',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-nephelometer-scattering',
    title: 'Himadri Integrating Nephelometer Aerosol Light Scattering',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Radiation & Optics',
    scientificDomain: 'Atmosphere',
    description: 'Multi-wavelength integrating nephelometer measurements of total scattering and backscattering coefficients at 450nm (blue), 525nm (green), and 635nm (red).',
    dateStart: '2019-01-01',
    dateEnd: '2021-12-31',
    variables: ['Total Scattering (Sca_G)', 'Backscattering (BSca_G)', 'Relative Humidity'],
    units: ['1/Mm', '1/Mm', '%'],
    fileFormat: 'CSV / ZIP',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-ctd-oceanography',
    title: 'Kongsfjorden Fjord Hydrographic CTD Ocean Profiles (2011–2017)',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Hydrography',
    scientificDomain: 'Ocean',
    description: 'Conductivity-Temperature-Depth (CTD) hydrographic profiles measured in Kongsfjorden fjord to track warming Atlantic water intrusions and glacial melt runoff.',
    dateStart: '2011-08-01',
    dateEnd: '2017-09-30',
    variables: ['Water Temperature', 'Salinity', 'Water Depth', 'Density'],
    units: ['°C', 'PSU', 'm', 'kg/m³'],
    fileFormat: 'ZIP / CDF NetCDF',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-radiometer-profiles',
    title: 'Himadri Ground-Based Microwave Radiometer Sounding (2018–2020)',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Radiation',
    scientificDomain: 'Atmosphere',
    description: 'Multi-channel passive microwave radiometer atmospheric brightness temperature and thermodynamic sounding up to 10 km altitude above Ny-Ålesund.',
    dateStart: '2018-06-01',
    dateEnd: '2020-02-28',
    variables: ['Zenith Brightness Temp', 'Integrated Water Vapor', 'Liquid Water Path'],
    units: ['K', 'kg/m²', 'g/m²'],
    fileFormat: 'CSV / ZIP',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-ott-weather-2018-2021',
    title: 'Himadri OTT Pluvio Optical Weather Disdrometer (2018–2021)',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Meteorology',
    scientificDomain: 'Atmosphere',
    description: 'High-latitude precipitation intensity, snow particle velocity spectra, and optical meteorological visibility recorded at Ny-Ålesund.',
    dateStart: '2018-04-19',
    dateEnd: '2021-12-31',
    variables: ['Precipitation Intensity', 'MOR Visibility', 'Snow Intensity'],
    units: ['mm/h', 'm', 'mm/h'],
    fileFormat: 'CSV / ZIP',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-adcp-currents',
    title: 'Kongsfjorden Mooring ADCP Ocean Current Velocity Array (2014–2017)',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Ocean Currents',
    scientificDomain: 'Ocean',
    description: 'Acoustic Doppler Current Profiler (ADCP) mooring array deployed in Kongsfjorden measuring deep fjord circulation and velocity vectors.',
    dateStart: '2014-08-01',
    dateEnd: '2017-09-30',
    variables: ['Eastward Current (u)', 'Northward Current (v)', 'Sea Water Temp'],
    units: ['m/s', 'm/s', '°C'],
    fileFormat: 'ZIP / NetCDF',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-micro-rain-radar',
    title: 'Himadri Micro Rain Radar (MRR) Vertical Cloud & Droplet Profiles',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Meteorology',
    scientificDomain: 'Atmosphere',
    description: 'Vertical Doppler radar reflectivity profiling of cloud microphysics and droplet spectra across 31 height ranges above Ny-Ålesund.',
    dateStart: '2014-01-01',
    dateEnd: '2017-12-31',
    variables: ['Radar Reflectivity (Z)', 'Doppler Velocity', 'Drop Size Spectrum'],
    units: ['dBZ', 'm/s', 'mm'],
    fileFormat: 'ZIP / CDF NetCDF',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'himadri-finfish-biodiversity',
    title: 'Kongsfjorden Marine Finfish Taxonomy & Ecological Inventory',
    station: 'Himadri',
    stationSlug: 'himadri',
    region: 'Arctic',
    datasetType: 'Marine Biology',
    scientificDomain: 'Environment',
    description: 'Taxonomic photographic and morphological inventory of High Arctic benthic finfish species (*Myoxocephalus scorpius*, *Gadus morhua*) captured during marine expeditions.',
    dateStart: '2015-01-01',
    dateEnd: '2020-12-31',
    variables: ['Taxon Identification', 'Species Morphology', 'Habitat Depth', 'Coordinates'],
    units: ['Taxon', 'cm', 'm', 'deg'],
    fileFormat: 'ZIP / Image Inventory Archive',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },

  // ===== BHARATI DATASETS =====
  {
    id: 'bharati-heavy-metal-geochemistry',
    title: 'Bharati Station & Larsemann Hills Heavy Metal Soil Geochemistry',
    station: 'Bharati',
    stationSlug: 'bharati',
    region: 'Antarctica',
    datasetType: 'Geochemistry',
    scientificDomain: 'Geophysics',
    description: 'Inductively Coupled Plasma Mass Spectrometry (ICP-MS/ICP-OES) element determination of trace heavy metals (Fe, Mn, Zn, Cu, Pb, Cd, Cr) in rock and sediment samples around Bharati Station.',
    dateStart: '2017-01-01',
    dateEnd: '2018-12-31',
    variables: ['Iron Concentration (Fe)', 'Manganese (Mn)', 'Zinc (Zn)', 'Lead (Pb)'],
    units: ['ppm', 'ppm', 'ppm', 'ppm'],
    fileFormat: 'Excel (.xlsx)',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
  {
    id: 'bharati-isea-expedition-series',
    title: '27th to 36th ISEA Expedition Polar Observations & Radiation Logs',
    station: 'Bharati',
    stationSlug: 'bharati',
    region: 'Antarctica',
    datasetType: 'Expedition Records',
    scientificDomain: 'Atmosphere',
    description: 'Multi-year scientific expedition records covering 27th ISEA (2007) through 36th ISEA (2017) captured during Southern Ocean transits and Bharati Station commissioning.',
    dateStart: '2007-01-01',
    dateEnd: '2017-12-31',
    variables: ['Black Carbon Concentration', 'Surface Solar Irradiation', 'Air Temperature'],
    units: ['ng/m³', 'W/m²', '°C'],
    fileFormat: 'Excel (.xlsx)',
    source: 'National Polar Data Centre (NCPOR)',
    officialSourceUrl: 'https://npdc.ncpor.res.in/',
  },
];
